### ISSUE TITLE
Data still get sent to the client when there is a server error.

### ISSUE THREAD

**Issue by maxwan** [mage/mage#91] opened 2017-07-12 06:09 UTC
Here is the user commands to reproduce the bug.
```
exports.acl = ['user'];

exports.execute = async function (state, gachaType) {
	const userId = state.actorId;

	state.emit(userId, 'test');

	throw new Error('server');
};
```

**Comment by ronkorving** [comment] 2017-07-12 15:10
Right now, this is by design. But I think it's unpractical design. I would like to suggest the following change in state semantics:

- a call to `state.error()` cleans out all queued events and resets archivist cache and queued operations.
- `state.close()` becomes a single path that distributes archivist changes and events, and ignores the error state.

That means that you can still explicitly emit events and make DB changes *after* setting the error state. But anything that was queued to happen up until the point of the error will not happen.

`state.error()` calls can be seen as `rollback`, and `state.distribute()` (and by implication `state.close()`) calls can be considered `commit`.

Thoughts?

**Comment by AlmirKadric** [comment] 2017-07-13 04:13
hmmm, I agree with @maxwan 
if there is an error, nothing should change or be sent
this is one of the reasons why we batch db ops and defer them to after the logs
I don't see why not doing the same for the event system would be by design @ronkorving 

As for the rest of your suggestion, i think it makes sense since data was written, but i don't see that in @maxwan question

**Comment by ronkorving** [comment] 2017-07-13 06:15
@AlmirKadric It's by design, because the code is very explicitly written this way: https://github.com/mage/mage/blob/master/lib/state/state.js#L521-L526

That doesn't mean we have to agree with the design :) But it is by design.

**Comment by stelcheck** [comment] 2017-07-14 04:41
I see two things here:

1. The implementation is just wrong.
2. However, I can think

**Comment by stelcheck** [comment] 2017-07-14 06:13
Whoops, sorry, did not realised I had closed this :/

**Comment by stelcheck** [comment] 2017-07-21 11:08
Any responses to my suggestion?

**Comment by ronkorving** [comment] 2017-07-25 05:55
What happened to responses to mine? :)
It wouldn't change the system much, would not introduce new semantics and allow for all use cases (and not just events-for-errors).

**Comment by stelcheck** [comment] 2017-07-25 06:38
My last response included something that was meant a comment to both your suggestion and the direction the thread was taking overall. Apologies for not being clearer.

More specifically, I don't like the idea that errors be emitted that way because they could be unintentionally cleared.

```javascript
state.emit('yodawg', 1)
state.error('he dead')
state.emit('error.hedead', 'he really dead')
state.error('ahahah nope') 
state.emit('error.ahahah.nope', 'he dead?')
```

That is according to what I understand of the current code (which may be wrong). You could also unintentionally think yourself to still be on the happy path, schedule DB changes, and ending up running them

Now, this being said, and again from what I understand, the error returned itself would already be overwritten anyhow.

The other issue I see with this is that I cannot see how this would look elegant with `async/await` user.

Instead, what I had in mind was simply to add `state.emitError`, and have error events always be prefixed by `error.`; these would always be emitted regardless of the success or failure of a call, and would work well under the `async/await` paradigm. The only drawback I see is that you would not be able to run archivist operations, which may be an issue for some types of features (one example that comes to mind would be storing a broken in-game session for debugging purposes).

**Comment by ronkorving** [comment] 2017-07-28 03:14
I acknowledge your point on async/await. My intention was to switch to `state.error()` for those specific situations, which works, but arguably is not very consistent or more important: obvious.

Small sidenote:

When it comes to implementation of any solution, I do very much like the idea of cleaning up when `state.error` is called. Things are immediately clean. Accidental database writes under *any* circumstances would be impossible. Mutations do not remain queued up only to be wiped out later.

I don't like the idea of auto-prefixing error names, because it assumes too much about use cases. And I think a dedicated function may not be *the* way given the existing API. I would like to propose this alternative to what you suggested:

Any time you emit an event, allow to flag it as "to be emitted, even in the case of error" (ie: force-emit). Example:

```js
// emit(actorIds, path, data, options)

state.emit(userId, 'myevent', { hello: 'there' }, { language: 'en', isJson: false, force: true });
```

The way I adapted the API signature *is* a breaking change, but one that will clean up this function properly IMHO. We could always introduce the force-flag as a new argument in a first fix to maintain BC, but I think an `options` object makes more sense. The function signature is already too convoluted, and it wouldn't hurt to deal with that while we're at it.

**Comment by stelcheck** [comment] 2017-07-28 06:59
Sounds good to me. But maybe call the option 'alwaysEmit' or something similar (I am not sure 'force' would be good enough).

**Closed** 2017-11-10 06:24 UTC
Labels: bug, semver-minor
