### ISSUE TITLE
Running a server twice on the same port reports no error

### ISSUE THREAD

**Issue by Tatsujinichi** [mage/mage#102] opened 2017-07-25 08:29 UTC
Running two different servers on the same port reports no error, but the second instance will be unusable.  I expect there to be an error if the port is in use.

**Comment by stelcheck** [comment] 2017-07-26 05:22
Can you provide us with a quick description of how to reproduce this issue?  Normally, MAGE should throw a fatal error and exit, so there might be something that we are overlooking which is triggered by how you start your two instances.

Also, just to confirm, are your instances running on your machine, or in Docker containers?

**Comment by stelcheck** [comment] 2017-07-30 15:44
So the issue here was as follow:

  1. Listen on 0.0.0.0:8080 (notice the wildcard)
  2. Go to 127.0.0.1:8080 - you should be able to reach the server
  3. Listen with another app on 127.0.0.1:8080 - you get no error
  4. The second app now responds on 127.0.0.1:8080 instead of the second one

Since some projects set 0.0.0.0 just to be able to share on their local network (or even just for simplicity), this may end up conflict with other MAGE-based game having a stricter host configuration. 

If you think about it, it make perfect sense; listen addresses are tuples of host IP - port, and matching is made to the closest matching addresss (going from memory here, so feel free to correct me). However, I can see this being a bit of a hassle, so it would perhaps be nice to find a way to warn the user?

@ronkorving @AlmirKadric suggestions welcome.

**Comment by christopherobin** [comment] 2017-07-31 02:59
This might be an OSX/Windows only issue? On linux if you listen on `0.0.0.0:8080` then you cannot listen on any other interface on the same port, here is how it behaves on my machine (node 8):

```rust
> const s1 = net.createServer();
undefined
> const s2 = net.createServer();
undefined
> s1.listen(8080); // wildcard listen
Server { ... }
> s2.listen(8080, '127.0.0.1'); // interface listen
Server { ... }
Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server.setupListenHandle [as _listen2] (net.js:1315:14)
    at listenInCluster (net.js:1363:12)
    at doListen (net.js:1489:7)
    at _combinedTickCallback (internal/process/next_tick.js:105:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)

```

**Comment by stelcheck** [comment] 2017-07-31 03:19
I believe the issue was reported for Mac, but please check with
@tatsujinichi for more details.

**Comment by AlmirKadric** [comment] 2017-07-31 03:21
i can confirm the above behaviour on windows, no error thrown
```
almir@AlmirKadricPC ~
$ node
> var net = require('net');
undefined
> var s1 = net.createServer();
undefined
> var s2 = net.createServer();
undefined
> s1.listen(8080)
Server {
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _connections: 0,
  _handle:
   TCP {
     bytesRead: 0,
     _externalStream: {},
     fd: -1,
     reading: false,
     owner: [Circular],
     onread: null,
     onconnection: [Function: onconnection],
     writeQueueSize: 0 },
  _usingSlaves: false,
  _slaves: [],
  _unref: false,
  allowHalfOpen: false,
  pauseOnConnect: false,
  _connectionKey: '6::::8080' }
> s2.listen(8080, '127.0.0.1')
Server {
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _connections: 0,
  _handle: null,
  _usingSlaves: false,
  _slaves: [],
  _unref: false,
  allowHalfOpen: false,
  pauseOnConnect: false }
```

**Comment by stelcheck** [comment] 2017-07-31 03:33
Not entirely sure if related, but this is rather interesing:
https://github.com/nodejs/node/issues/7200#issuecomment-224405753


It does appear as it might be either a Node.js technical choice or a
system-specific configuration. Depending on which it is, we might be able
to set up platform agnostic warning or errors (I am assuming Node wouldn't
want to change its current behavior)

On Jul 31, 2017 12:21 PM, "Almir Kadric" <notifications@github.com> wrote:

i can confirm the above behaviour on windows, no error thrown

almir@AlmirKadricPC ~
$ node
> var net = require('net');
undefined
> var s1 = net.createServer();
undefined
> var s2 = net.createServer();
undefined
> s1.listen(8080)
Server {
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _connections: 0,
  _handle:
   TCP {
     bytesRead: 0,
     _externalStream: {},
     fd: -1,
     reading: false,
     owner: [Circular],
     onread: null,
     onconnection: [Function: onconnection],
     writeQueueSize: 0 },
  _usingSlaves: false,
  _slaves: [],
  _unref: false,
  allowHalfOpen: false,
  pauseOnConnect: false,
  _connectionKey: '6::::8080' }
> s2.listen(8080, '127.0.0.1')
Server {
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _connections: 0,
  _handle: null,
  _usingSlaves: false,
  _slaves: [],
  _unref: false,
  allowHalfOpen: false,
  pauseOnConnect: false }

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mage/mage/issues/102#issuecomment-318958115>, or mute
the thread

**Comment by christopherobin** [comment] 2017-07-31 03:35
It might be node? Notice how the second connection on windows does not seem to get an `_handle`, indicating that it probably doesn't work?

**Comment by stelcheck** [comment] 2017-07-31 04:03
I would assume the opposite, or more specifically that node behaves like
this because of platform specific behaviors. In this case, could it be that
it internally piggybacks the wildcard handle internally?

**Comment by stelcheck** [comment] 2017-08-04 03:15
I created an issue on the node repo; I guess they will be able to let us know more quickly what might be going on here.

**Comment by stelcheck** [comment] 2017-08-04 07:15
According to the issue thread, this is an OS-specific issue which would affect most languages. 

While we could try to protect developers against that, I feel we would potentially introduce more problems, and even go against future user expectations. I will close this issue for now, but please feel free to re-open if you can think of a viable alternative for safely protecting developers against this kind of issues.

**Closed by stelcheck** 2017-08-04 07:15 UTC
